packages/common/components/blocks/ad/emailx.marko, packages/common/components/blocks/ad/marko.json, packages/common/components/blocks/ad/promotion-advertisement.marko, packages/common/components/blocks/ad/promotion-native.marko, packages/common/components/blocks/ad/promotion-sponsored.marko, packages/common/components/blocks/ad/wrapper.marko, packages/common/components/blocks/body-wrapper.marko, packages/common/components/blocks/content/background.marko, packages/common/components/blocks/content/list-item.marko, packages/common/components/blocks/content/list.marko, packages/common/components/blocks/content/marko.json, packages/common/components/blocks/footer.marko, packages/common/components/blocks/head.marko, packages/common/components/blocks/header.marko, packages/common/components/blocks/marko.json, packages/common/components/blocks/view-online.marko, packages/common/components/elements/cta.marko, packages/common/components/elements/link.marko, packages/common/components/elements/list-header.marko, packages/common/components/elements/logo.marko, packages/common/components/elements/marko.json, packages/common/components/elements/table-hr.marko, packages/common/components/elements/table-spacer.marko, packages/common/components/layouts/marko.json, packages/common/components/layouts/standard.marko, tenants/all/config/brands.js, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/lab-pulse-insight.marko
=> Add initial components folders/files & basic lab pulse insights template setup

packages/common/components/blocks/footer.marko, tenants/all/config/brands.js, tenants/all/config/core.js
=> Update unsubscribe text in footer

packages/common/components/blocks/ad/promotion-advertisement.marko, packages/common/components/blocks/ad/promotion-sponsored.marko, packages/common/components/blocks/content/background.marko, packages/common/components/blocks/content/list-item.marko, packages/common/components/blocks/footer.marko, packages/common/components/blocks/view-online.marko, packages/common/components/elements/link.marko, packages/common/components/elements/logo.marko, packages/common/utils/build-link-url.js, tenants/all/config/core.js
Also fixes URL encoding issue with preference center link
=> Add Braze External ID tracking to links

packages/common/components/layouts/standard.marko
This will only allow 10 total content pieces in the 'Main' section
=> Set limit to 8

tenants/all/config/brands.js, tenants/all/config/core.js
=> Update 'logo' images

packages/common/components/blocks/ad/promotion-advertisement.marko, packages/common/components/blocks/ad/promotion-native.marko, packages/common/components/blocks/ad/promotion-sponsored.marko, packages/common/components/blocks/ad/wrapper.marko
=> Remove linkLabelProps

tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/templates/testing-template.marko
=> Create testing template for ads

packages/common/components/layouts/case.marko, tenants/all/config/email-x.js
=> Add EmailX ad to Case of the Week layout

packages/common/components/blocks/content/api-list-item.marko, packages/common/components/blocks/external-api.marko
=> Display ‘shortName’ for Case of the Week block/API call

packages/common/components/blocks/footer.marko, tenants/all/config/core.js
=> Update footer logo for 'Sample' template

tenants/all/templates/drb-lfte.marko
=> Dr.B-LFTE: move ‘Editor’s Note’ to 1st slot and 3rd slot add image

packages/common/components/layouts/case.marko, packages/common/components/layouts/marko.json, packages/common/components/layouts/radcast.marko, tenants/all/config/brands.js, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/am-breaking-news.marko, tenants/all/templates/am-case-of-the-week.marko, tenants/all/templates/am-community-insider.marko, tenants/all/templates/am-lfte.marko, tenants/all/templates/am-radcast.marko, tenants/all/templates/drb-lfte.marko
=> Create Auntminnie newsletters

tenants/all/config/core.js
=> Update Case of the Week headers

tenants/all/templates/am-lfte.marko
=> Increase limit of am-lfte to 45

packages/common/components/layouts/insider.marko, tenants/all/templates/am-community-insider.marko
=> Add ability to set display limit & set amInsider to 16

packages/common/package.json, tenants/all/config/email-x.js, tenants/all/config/native-x.js, yarn.lock
Reverts parameter1/science-medicine-group-newsletters#34
=> Revert "Use compat api for email-x and native-x"

packages/common/components/blocks/content/list.marko, packages/common/components/elements/list-header.marko, tenants/all/templates/drb-lfte.marko
=> Set specific header color for DrB 'In case you missed it' block

packages/common/components/blocks/footer.marko
=> Fix spelling of ‘recieving’

tenants/all/config/brands.js, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/ame-breaking-news.marko, tenants/all/templates/ame-case-of-the-week.marko, tenants/all/templates/ame-community-insider.marko, tenants/all/templates/ame-lfte.marko, tenants/all/templates/ame-radcast.marko
the image path is 'broke' I think it has to do with connecting to staging and since auntminnieeurope.com isn't 'ours' yet.
=> Setup AME newsletters

packages/common/components/layouts/marko.json, packages/common/components/layouts/rsna.marko, tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/templates/am-rsna-preview.marko, tenants/all/templates/am-rsna.marko
=> Create RSNA layout and newsletters

tenants/all/config/core.js
=> Update header for RSNA & Radcast for AuntMinnie

tenants/all/templates/drb-community-insider.marko
=> Add images to DrB Community Insider

tenants/all/config/core.js
=> Update preferenceCenter url for am-lfte

packages/common/components/blocks/am-footer.marko, packages/common/components/blocks/marko.json, packages/common/components/layouts/breaking-news.marko, packages/common/components/layouts/insider.marko, packages/common/components/layouts/senl.marko, tenants/all/config/core.js, tenants/all/templates/am-breaking-news.marko, tenants/all/templates/am-case-of-the-week.marko, tenants/all/templates/am-community-insider.marko, tenants/all/templates/am-lfte.marko, tenants/all/templates/am-senl.marko, tenants/all/templates/ame-lfte.marko
=> Update AM and AME-LFTE footer block to go to my.auntminnie preference center

tenants/all/config/core.js
=> Update header image

tenants/all/config/email-x.js, tenants/all/templates/am-lfte.marko
=> Create RADCast section and ad in AM-LFTE

tenants/all/templates/am-lfte.marko
=> Change “Main” to “Radiology News” - AM-LFTE

tenants/all/templates/am-lfte.marko
=> Change ‘Case’ to ‘Cases’ for AM-LFTE

packages/common/components/blocks/body-wrapper.marko, packages/common/components/blocks/footer.marko, packages/common/components/blocks/new-footer.marko, packages/common/components/elements/marko.json, packages/common/components/elements/stealth-link.marko
Reverts parameter1/science-medicine-group-newsletters#74
=> Revert "Remove stealth link from all newsletters"

packages/common/components/blocks/ad/marko.json, packages/common/components/blocks/ad/promotion-25-for-25.marko, packages/common/components/blocks/ad/wrapper.marko, packages/common/components/blocks/content/25-for-25.marko, packages/common/components/blocks/content/marko.json, tenants/all/templates/am-lfte.marko
=> Create 25 for 25 Native block AM-LFTE

tenants/all/config/core.js
=> Update logos for AM-LFTE & Insider

tenants/all/templates/am-lfte.marko, tenants/all/templates/drb-lfte.marko
=> Reduce total Cases being returned to 1 for DrB & AM - LFTE

tenants/all/templates/am-lfte.marko
=> Change Cases to 'Case of the Week'

tenants/all/config/core.js, tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/am-weekly.marko
=> Create AM Weekly

tenants/all/config/core.js
=> Add caseBlock to core.js file for am-weekly

tenants/all/config/email-x.js, tenants/all/config/native-x.js, tenants/all/templates/drb-lfte.marko
=> Create new ad slot for DrB - LFTE

tenants/all/templates/drb-lfte.marko
=> Create 'Community Insider' block to DrB-LFTE and rename Main section to Top Stories

tenants/all/config/email-x.js, tenants/all/templates/am-lfte.marko
=> Create new section & ad unit AM-LFTE

packages/common/components/blocks/content/list-item.marko
=> Remove sponsored label

packages/common/components/layouts/standard.marko
=> Move ‘Editor’s Note’ to top of Lab LFTE

tenants/all/templates/am-lfte.marko
=> Add images to Radcast articles 1 & 3

tenants/all/config/core.js
=> Update logos AME, DrB, LP lfte newsletters

tenants/all/templates/drb-lfte.marko
=> Move ‘case’ ad below case api

tenants/all/templates/ame-radcast.marko
Removed the limit since they keep increasing it anyways
=> Remove limit on AME Radcast

tenants/all/templates/am-lfte.marko
=> Increase limit on Radcast section AM-LFTE

tenants/all/templates/drb-sample.marko
=> Add static text to DrB sample template
